# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  reconnect: false
  encoding: utf8
  pool: 5
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: teamtracker_development

test:
  <<: *default
  database: teamtracker_test
  min_messages: WARNING
